//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  solution: Solution;
  solutionConnection: SolutionConnection;
  industry: Industry;
  industryConnection: IndustryConnection;
  navigation: Navigation;
  navigationConnection: NavigationConnection;
  brand: Brand;
  brandConnection: BrandConnection;
  footer: Footer;
  footerConnection: FooterConnection;
  global: Global;
  globalConnection: GlobalConnection;
  clientLogo: ClientLogo;
  clientLogoConnection: ClientLogoConnection;
  country: Country;
  countryConnection: CountryConnection;
  whyMyelektra: WhyMyelektra;
  whyMyelektraConnection: WhyMyelektraConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QuerySolutionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySolutionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SolutionFilter>;
};


export type QueryIndustryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIndustryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IndustryFilter>;
};


export type QueryNavigationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavigationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavigationFilter>;
};


export type QueryBrandArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBrandConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BrandFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryClientLogoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryClientLogoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ClientLogoFilter>;
};


export type QueryCountryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCountryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CountryFilter>;
};


export type QueryWhyMyelektraArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWhyMyelektraConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WhyMyelektraFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  solution?: InputMaybe<SolutionFilter>;
  industry?: InputMaybe<IndustryFilter>;
  navigation?: InputMaybe<NavigationFilter>;
  brand?: InputMaybe<BrandFilter>;
  footer?: InputMaybe<FooterFilter>;
  global?: InputMaybe<GlobalFilter>;
  clientLogo?: InputMaybe<ClientLogoFilter>;
  country?: InputMaybe<CountryFilter>;
  whyMyelektra?: InputMaybe<WhyMyelektraFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Solution | Industry | Navigation | Brand | Footer | Global | ClientLogo | Country | WhyMyelektra | Folder;

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  heroHeadline?: Maybe<Scalars['String']['output']>;
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroCtaLabel?: Maybe<Scalars['String']['output']>;
  heroCtaPath?: Maybe<Scalars['String']['output']>;
  storyLabel?: Maybe<Scalars['String']['output']>;
  storyHeadline?: Maybe<Scalars['String']['output']>;
  storyParagraph1?: Maybe<Scalars['String']['output']>;
  storyParagraph2?: Maybe<Scalars['String']['output']>;
  missionHeadline?: Maybe<Scalars['String']['output']>;
  missionText?: Maybe<Scalars['String']['output']>;
  statsHeadline?: Maybe<Scalars['String']['output']>;
  includedLabel?: Maybe<Scalars['String']['output']>;
  popularBadge?: Maybe<Scalars['String']['output']>;
  personasHeadline?: Maybe<Scalars['String']['output']>;
  ctaHeadline?: Maybe<Scalars['String']['output']>;
  ctaBody?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  ctaButtonPath?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroCtaLabel?: InputMaybe<StringFilter>;
  heroCtaPath?: InputMaybe<StringFilter>;
  storyLabel?: InputMaybe<StringFilter>;
  storyHeadline?: InputMaybe<StringFilter>;
  storyParagraph1?: InputMaybe<StringFilter>;
  storyParagraph2?: InputMaybe<StringFilter>;
  missionHeadline?: InputMaybe<StringFilter>;
  missionText?: InputMaybe<StringFilter>;
  statsHeadline?: InputMaybe<StringFilter>;
  includedLabel?: InputMaybe<StringFilter>;
  popularBadge?: InputMaybe<StringFilter>;
  personasHeadline?: InputMaybe<StringFilter>;
  ctaHeadline?: InputMaybe<StringFilter>;
  ctaBody?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
  ctaButtonPath?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type SolutionSteps = {
  __typename?: 'SolutionSteps';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Solution = Node & Document & {
  __typename?: 'Solution';
  title: Scalars['String']['output'];
  price?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  isPopular?: Maybe<Scalars['Boolean']['output']>;
  bestFor?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  steps?: Maybe<Array<Maybe<SolutionSteps>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SolutionStepsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SolutionFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  isPopular?: InputMaybe<BooleanFilter>;
  bestFor?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  steps?: InputMaybe<SolutionStepsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SolutionConnectionEdges = {
  __typename?: 'SolutionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Solution>;
};

export type SolutionConnection = Connection & {
  __typename?: 'SolutionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SolutionConnectionEdges>>>;
};

export type IndustryPersonas = {
  __typename?: 'IndustryPersonas';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Industry = Node & Document & {
  __typename?: 'Industry';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  personas?: Maybe<Array<Maybe<IndustryPersonas>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type IndustryPersonasFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type IndustryFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  personas?: InputMaybe<IndustryPersonasFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type IndustryConnectionEdges = {
  __typename?: 'IndustryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Industry>;
};

export type IndustryConnection = Connection & {
  __typename?: 'IndustryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IndustryConnectionEdges>>>;
};

export type NavigationDesktopSubmenu = {
  __typename?: 'NavigationDesktopSubmenu';
  label?: Maybe<Scalars['String']['output']>;
  path?: Maybe<Scalars['String']['output']>;
};

export type NavigationDesktop = {
  __typename?: 'NavigationDesktop';
  label?: Maybe<Scalars['String']['output']>;
  path?: Maybe<Scalars['String']['output']>;
  submenu?: Maybe<Array<Maybe<NavigationDesktopSubmenu>>>;
};

export type Navigation = Node & Document & {
  __typename?: 'Navigation';
  desktop?: Maybe<Array<Maybe<NavigationDesktop>>>;
  headerCta?: Maybe<Scalars['String']['output']>;
  headerCtaPath?: Maybe<Scalars['String']['output']>;
  hideFromNav?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavigationDesktopSubmenuFilter = {
  label?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
};

export type NavigationDesktopFilter = {
  label?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
  submenu?: InputMaybe<NavigationDesktopSubmenuFilter>;
};

export type NavigationFilter = {
  desktop?: InputMaybe<NavigationDesktopFilter>;
  headerCta?: InputMaybe<StringFilter>;
  headerCtaPath?: InputMaybe<StringFilter>;
  hideFromNav?: InputMaybe<StringFilter>;
};

export type NavigationConnectionEdges = {
  __typename?: 'NavigationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Navigation>;
};

export type NavigationConnection = Connection & {
  __typename?: 'NavigationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavigationConnectionEdges>>>;
};

export type BrandAddress = {
  __typename?: 'BrandAddress';
  line1?: Maybe<Scalars['String']['output']>;
  line2?: Maybe<Scalars['String']['output']>;
  country?: Maybe<Scalars['String']['output']>;
};

export type BrandSocial = {
  __typename?: 'BrandSocial';
  linkedin?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
};

export type BrandFounder = {
  __typename?: 'BrandFounder';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
};

export type BrandLogo = {
  __typename?: 'BrandLogo';
  file?: Maybe<Scalars['String']['output']>;
};

export type Brand = Node & Document & {
  __typename?: 'Brand';
  company?: Maybe<Scalars['String']['output']>;
  domain?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  subTagline?: Maybe<Scalars['String']['output']>;
  positioning?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  address?: Maybe<BrandAddress>;
  hours?: Maybe<Scalars['String']['output']>;
  social?: Maybe<BrandSocial>;
  founder?: Maybe<BrandFounder>;
  logo?: Maybe<BrandLogo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BrandAddressFilter = {
  line1?: InputMaybe<StringFilter>;
  line2?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
};

export type BrandSocialFilter = {
  linkedin?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BrandFounderFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  linkedin?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
};

export type BrandLogoFilter = {
  file?: InputMaybe<ImageFilter>;
};

export type BrandFilter = {
  company?: InputMaybe<StringFilter>;
  domain?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  subTagline?: InputMaybe<StringFilter>;
  positioning?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  address?: InputMaybe<BrandAddressFilter>;
  hours?: InputMaybe<StringFilter>;
  social?: InputMaybe<BrandSocialFilter>;
  founder?: InputMaybe<BrandFounderFilter>;
  logo?: InputMaybe<BrandLogoFilter>;
};

export type BrandConnectionEdges = {
  __typename?: 'BrandConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Brand>;
};

export type BrandConnection = Connection & {
  __typename?: 'BrandConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BrandConnectionEdges>>>;
};

export type FooterColumnsLinks = {
  __typename?: 'FooterColumnsLinks';
  label?: Maybe<Scalars['String']['output']>;
  path?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
};

export type FooterColumns = {
  __typename?: 'FooterColumns';
  title?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<FooterColumnsLinks>>>;
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  columns?: Maybe<Array<Maybe<FooterColumns>>>;
  copyright?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterColumnsLinksFilter = {
  label?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
};

export type FooterColumnsFilter = {
  title?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  links?: InputMaybe<FooterColumnsLinksFilter>;
};

export type FooterFilter = {
  columns?: InputMaybe<FooterColumnsFilter>;
  copyright?: InputMaybe<StringFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type GlobalFloatingCta = {
  __typename?: 'GlobalFloatingCta';
  text?: Maybe<Scalars['String']['output']>;
  buttonLabel?: Maybe<Scalars['String']['output']>;
  buttonPath?: Maybe<Scalars['String']['output']>;
  showAfterScrollPx?: Maybe<Scalars['Float']['output']>;
};

export type GlobalBackToTop = {
  __typename?: 'GlobalBackToTop';
  showAfterScrollPx?: Maybe<Scalars['Float']['output']>;
};

export type GlobalCookieBanner = {
  __typename?: 'GlobalCookieBanner';
  text?: Maybe<Scalars['String']['output']>;
  acceptLabel?: Maybe<Scalars['String']['output']>;
  learnMoreLabel?: Maybe<Scalars['String']['output']>;
};

export type GlobalScrollAnimation = {
  __typename?: 'GlobalScrollAnimation';
  enabled?: Maybe<Scalars['Boolean']['output']>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  floatingCta?: Maybe<GlobalFloatingCta>;
  backToTop?: Maybe<GlobalBackToTop>;
  cookieBanner?: Maybe<GlobalCookieBanner>;
  scrollAnimation?: Maybe<GlobalScrollAnimation>;
  disclaimer?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type GlobalFloatingCtaFilter = {
  text?: InputMaybe<StringFilter>;
  buttonLabel?: InputMaybe<StringFilter>;
  buttonPath?: InputMaybe<StringFilter>;
  showAfterScrollPx?: InputMaybe<NumberFilter>;
};

export type GlobalBackToTopFilter = {
  showAfterScrollPx?: InputMaybe<NumberFilter>;
};

export type GlobalCookieBannerFilter = {
  text?: InputMaybe<StringFilter>;
  acceptLabel?: InputMaybe<StringFilter>;
  learnMoreLabel?: InputMaybe<StringFilter>;
};

export type GlobalScrollAnimationFilter = {
  enabled?: InputMaybe<BooleanFilter>;
};

export type GlobalFilter = {
  floatingCta?: InputMaybe<GlobalFloatingCtaFilter>;
  backToTop?: InputMaybe<GlobalBackToTopFilter>;
  cookieBanner?: InputMaybe<GlobalCookieBannerFilter>;
  scrollAnimation?: InputMaybe<GlobalScrollAnimationFilter>;
  disclaimer?: InputMaybe<StringFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type ClientLogo = Node & Document & {
  __typename?: 'ClientLogo';
  title: Scalars['String']['output'];
  logo?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ClientLogoFilter = {
  title?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  website?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ClientLogoConnectionEdges = {
  __typename?: 'ClientLogoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ClientLogo>;
};

export type ClientLogoConnection = Connection & {
  __typename?: 'ClientLogoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ClientLogoConnectionEdges>>>;
};

export type CountryPersonas = {
  __typename?: 'CountryPersonas';
  name?: Maybe<Scalars['String']['output']>;
};

export type Country = Node & Document & {
  __typename?: 'Country';
  title: Scalars['String']['output'];
  flagAccent?: Maybe<Scalars['String']['output']>;
  personas?: Maybe<Array<Maybe<CountryPersonas>>>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CountryPersonasFilter = {
  name?: InputMaybe<StringFilter>;
};

export type CountryFilter = {
  title?: InputMaybe<StringFilter>;
  flagAccent?: InputMaybe<StringFilter>;
  personas?: InputMaybe<CountryPersonasFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type CountryConnectionEdges = {
  __typename?: 'CountryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Country>;
};

export type CountryConnection = Connection & {
  __typename?: 'CountryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CountryConnectionEdges>>>;
};

export type WhyMyelektra = Node & Document & {
  __typename?: 'WhyMyelektra';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WhyMyelektraFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type WhyMyelektraConnectionEdges = {
  __typename?: 'WhyMyelektraConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<WhyMyelektra>;
};

export type WhyMyelektraConnection = Connection & {
  __typename?: 'WhyMyelektraConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WhyMyelektraConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateSolution: Solution;
  createSolution: Solution;
  updateIndustry: Industry;
  createIndustry: Industry;
  updateNavigation: Navigation;
  createNavigation: Navigation;
  updateBrand: Brand;
  createBrand: Brand;
  updateFooter: Footer;
  createFooter: Footer;
  updateGlobal: Global;
  createGlobal: Global;
  updateClientLogo: ClientLogo;
  createClientLogo: ClientLogo;
  updateCountry: Country;
  createCountry: Country;
  updateWhyMyelektra: WhyMyelektra;
  createWhyMyelektra: WhyMyelektra;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateSolutionArgs = {
  relativePath: Scalars['String']['input'];
  params: SolutionMutation;
};


export type MutationCreateSolutionArgs = {
  relativePath: Scalars['String']['input'];
  params: SolutionMutation;
};


export type MutationUpdateIndustryArgs = {
  relativePath: Scalars['String']['input'];
  params: IndustryMutation;
};


export type MutationCreateIndustryArgs = {
  relativePath: Scalars['String']['input'];
  params: IndustryMutation;
};


export type MutationUpdateNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: NavigationMutation;
};


export type MutationCreateNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: NavigationMutation;
};


export type MutationUpdateBrandArgs = {
  relativePath: Scalars['String']['input'];
  params: BrandMutation;
};


export type MutationCreateBrandArgs = {
  relativePath: Scalars['String']['input'];
  params: BrandMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationUpdateClientLogoArgs = {
  relativePath: Scalars['String']['input'];
  params: ClientLogoMutation;
};


export type MutationCreateClientLogoArgs = {
  relativePath: Scalars['String']['input'];
  params: ClientLogoMutation;
};


export type MutationUpdateCountryArgs = {
  relativePath: Scalars['String']['input'];
  params: CountryMutation;
};


export type MutationCreateCountryArgs = {
  relativePath: Scalars['String']['input'];
  params: CountryMutation;
};


export type MutationUpdateWhyMyelektraArgs = {
  relativePath: Scalars['String']['input'];
  params: WhyMyelektraMutation;
};


export type MutationCreateWhyMyelektraArgs = {
  relativePath: Scalars['String']['input'];
  params: WhyMyelektraMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  solution?: InputMaybe<SolutionMutation>;
  industry?: InputMaybe<IndustryMutation>;
  navigation?: InputMaybe<NavigationMutation>;
  brand?: InputMaybe<BrandMutation>;
  footer?: InputMaybe<FooterMutation>;
  global?: InputMaybe<GlobalMutation>;
  clientLogo?: InputMaybe<ClientLogoMutation>;
  country?: InputMaybe<CountryMutation>;
  whyMyelektra?: InputMaybe<WhyMyelektraMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  solution?: InputMaybe<SolutionMutation>;
  industry?: InputMaybe<IndustryMutation>;
  navigation?: InputMaybe<NavigationMutation>;
  brand?: InputMaybe<BrandMutation>;
  footer?: InputMaybe<FooterMutation>;
  global?: InputMaybe<GlobalMutation>;
  clientLogo?: InputMaybe<ClientLogoMutation>;
  country?: InputMaybe<CountryMutation>;
  whyMyelektra?: InputMaybe<WhyMyelektraMutation>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroCtaLabel?: InputMaybe<Scalars['String']['input']>;
  heroCtaPath?: InputMaybe<Scalars['String']['input']>;
  storyLabel?: InputMaybe<Scalars['String']['input']>;
  storyHeadline?: InputMaybe<Scalars['String']['input']>;
  storyParagraph1?: InputMaybe<Scalars['String']['input']>;
  storyParagraph2?: InputMaybe<Scalars['String']['input']>;
  missionHeadline?: InputMaybe<Scalars['String']['input']>;
  missionText?: InputMaybe<Scalars['String']['input']>;
  statsHeadline?: InputMaybe<Scalars['String']['input']>;
  includedLabel?: InputMaybe<Scalars['String']['input']>;
  popularBadge?: InputMaybe<Scalars['String']['input']>;
  personasHeadline?: InputMaybe<Scalars['String']['input']>;
  ctaHeadline?: InputMaybe<Scalars['String']['input']>;
  ctaBody?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
  ctaButtonPath?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SolutionStepsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SolutionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  isPopular?: InputMaybe<Scalars['Boolean']['input']>;
  bestFor?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  steps?: InputMaybe<Array<InputMaybe<SolutionStepsMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type IndustryPersonasMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type IndustryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  personas?: InputMaybe<Array<InputMaybe<IndustryPersonasMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NavigationDesktopSubmenuMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
};

export type NavigationDesktopMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  submenu?: InputMaybe<Array<InputMaybe<NavigationDesktopSubmenuMutation>>>;
};

export type NavigationMutation = {
  desktop?: InputMaybe<Array<InputMaybe<NavigationDesktopMutation>>>;
  headerCta?: InputMaybe<Scalars['String']['input']>;
  headerCtaPath?: InputMaybe<Scalars['String']['input']>;
  hideFromNav?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BrandAddressMutation = {
  line1?: InputMaybe<Scalars['String']['input']>;
  line2?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
};

export type BrandSocialMutation = {
  linkedin?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
};

export type BrandFounderMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
};

export type BrandLogoMutation = {
  file?: InputMaybe<Scalars['String']['input']>;
};

export type BrandMutation = {
  company?: InputMaybe<Scalars['String']['input']>;
  domain?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  subTagline?: InputMaybe<Scalars['String']['input']>;
  positioning?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<BrandAddressMutation>;
  hours?: InputMaybe<Scalars['String']['input']>;
  social?: InputMaybe<BrandSocialMutation>;
  founder?: InputMaybe<BrandFounderMutation>;
  logo?: InputMaybe<BrandLogoMutation>;
};

export type FooterColumnsLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FooterColumnsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<FooterColumnsLinksMutation>>>;
};

export type FooterMutation = {
  columns?: InputMaybe<Array<InputMaybe<FooterColumnsMutation>>>;
  copyright?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalFloatingCtaMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  buttonLabel?: InputMaybe<Scalars['String']['input']>;
  buttonPath?: InputMaybe<Scalars['String']['input']>;
  showAfterScrollPx?: InputMaybe<Scalars['Float']['input']>;
};

export type GlobalBackToTopMutation = {
  showAfterScrollPx?: InputMaybe<Scalars['Float']['input']>;
};

export type GlobalCookieBannerMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  acceptLabel?: InputMaybe<Scalars['String']['input']>;
  learnMoreLabel?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalScrollAnimationMutation = {
  enabled?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GlobalMutation = {
  floatingCta?: InputMaybe<GlobalFloatingCtaMutation>;
  backToTop?: InputMaybe<GlobalBackToTopMutation>;
  cookieBanner?: InputMaybe<GlobalCookieBannerMutation>;
  scrollAnimation?: InputMaybe<GlobalScrollAnimationMutation>;
  disclaimer?: InputMaybe<Scalars['String']['input']>;
};

export type ClientLogoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type CountryPersonasMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
};

export type CountryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  flagAccent?: InputMaybe<Scalars['String']['input']>;
  personas?: InputMaybe<Array<InputMaybe<CountryPersonasMutation>>>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type WhyMyelektraMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type PagePartsFragment = { __typename: 'Page', title: string, description?: string | null, ogImage?: string | null, draft?: boolean | null, heroHeadline?: string | null, heroSubtitle?: string | null, heroCtaLabel?: string | null, heroCtaPath?: string | null, storyLabel?: string | null, storyHeadline?: string | null, storyParagraph1?: string | null, storyParagraph2?: string | null, missionHeadline?: string | null, missionText?: string | null, statsHeadline?: string | null, includedLabel?: string | null, popularBadge?: string | null, personasHeadline?: string | null, ctaHeadline?: string | null, ctaBody?: string | null, ctaButtonLabel?: string | null, ctaButtonPath?: string | null, body?: any | null };

export type SolutionPartsFragment = { __typename: 'Solution', title: string, price?: string | null, description?: string | null, icon?: string | null, isPopular?: boolean | null, bestFor?: string | null, cta?: string | null, metaTitle?: string | null, metaDescription?: string | null, body?: any | null, steps?: Array<{ __typename: 'SolutionSteps', title?: string | null, description?: string | null } | null> | null };

export type IndustryPartsFragment = { __typename: 'Industry', title: string, description?: string | null, icon?: string | null, metaTitle?: string | null, metaDescription?: string | null, body?: any | null, personas?: Array<{ __typename: 'IndustryPersonas', name?: string | null, description?: string | null } | null> | null };

export type NavigationPartsFragment = { __typename: 'Navigation', headerCta?: string | null, headerCtaPath?: string | null, hideFromNav?: Array<string | null> | null, desktop?: Array<{ __typename: 'NavigationDesktop', label?: string | null, path?: string | null, submenu?: Array<{ __typename: 'NavigationDesktopSubmenu', label?: string | null, path?: string | null } | null> | null } | null> | null };

export type BrandPartsFragment = { __typename: 'Brand', company?: string | null, domain?: string | null, tagline?: string | null, subTagline?: string | null, positioning?: string | null, phone?: string | null, email?: string | null, hours?: string | null, address?: { __typename: 'BrandAddress', line1?: string | null, line2?: string | null, country?: string | null } | null, social?: { __typename: 'BrandSocial', linkedin?: string | null, instagram?: string | null } | null, founder?: { __typename: 'BrandFounder', name?: string | null, title?: string | null, photo?: string | null, linkedin?: string | null, instagram?: string | null } | null, logo?: { __typename: 'BrandLogo', file?: string | null } | null };

export type FooterPartsFragment = { __typename: 'Footer', copyright?: string | null, columns?: Array<{ __typename: 'FooterColumns', title?: string | null, type?: string | null, links?: Array<{ __typename: 'FooterColumnsLinks', label?: string | null, path?: string | null, highlight?: boolean | null } | null> | null } | null> | null };

export type GlobalPartsFragment = { __typename: 'Global', disclaimer?: string | null, floatingCta?: { __typename: 'GlobalFloatingCta', text?: string | null, buttonLabel?: string | null, buttonPath?: string | null, showAfterScrollPx?: number | null } | null, backToTop?: { __typename: 'GlobalBackToTop', showAfterScrollPx?: number | null } | null, cookieBanner?: { __typename: 'GlobalCookieBanner', text?: string | null, acceptLabel?: string | null, learnMoreLabel?: string | null } | null, scrollAnimation?: { __typename: 'GlobalScrollAnimation', enabled?: boolean | null } | null };

export type ClientLogoPartsFragment = { __typename: 'ClientLogo', title: string, logo?: string | null, website?: string | null, order?: number | null };

export type CountryPartsFragment = { __typename: 'Country', title: string, flagAccent?: string | null, order?: number | null, personas?: Array<{ __typename: 'CountryPersonas', name?: string | null } | null> | null };

export type WhyMyelektraPartsFragment = { __typename: 'WhyMyelektra', title: string, description?: string | null, icon?: string | null, order?: number | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, description?: string | null, ogImage?: string | null, draft?: boolean | null, heroHeadline?: string | null, heroSubtitle?: string | null, heroCtaLabel?: string | null, heroCtaPath?: string | null, storyLabel?: string | null, storyHeadline?: string | null, storyParagraph1?: string | null, storyParagraph2?: string | null, missionHeadline?: string | null, missionText?: string | null, statsHeadline?: string | null, includedLabel?: string | null, popularBadge?: string | null, personasHeadline?: string | null, ctaHeadline?: string | null, ctaBody?: string | null, ctaButtonLabel?: string | null, ctaButtonPath?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, description?: string | null, ogImage?: string | null, draft?: boolean | null, heroHeadline?: string | null, heroSubtitle?: string | null, heroCtaLabel?: string | null, heroCtaPath?: string | null, storyLabel?: string | null, storyHeadline?: string | null, storyParagraph1?: string | null, storyParagraph2?: string | null, missionHeadline?: string | null, missionText?: string | null, statsHeadline?: string | null, includedLabel?: string | null, popularBadge?: string | null, personasHeadline?: string | null, ctaHeadline?: string | null, ctaBody?: string | null, ctaButtonLabel?: string | null, ctaButtonPath?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SolutionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SolutionQuery = { __typename?: 'Query', solution: { __typename: 'Solution', id: string, title: string, price?: string | null, description?: string | null, icon?: string | null, isPopular?: boolean | null, bestFor?: string | null, cta?: string | null, metaTitle?: string | null, metaDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, steps?: Array<{ __typename: 'SolutionSteps', title?: string | null, description?: string | null } | null> | null } };

export type SolutionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SolutionFilter>;
}>;


export type SolutionConnectionQuery = { __typename?: 'Query', solutionConnection: { __typename?: 'SolutionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SolutionConnectionEdges', cursor: string, node?: { __typename: 'Solution', id: string, title: string, price?: string | null, description?: string | null, icon?: string | null, isPopular?: boolean | null, bestFor?: string | null, cta?: string | null, metaTitle?: string | null, metaDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, steps?: Array<{ __typename: 'SolutionSteps', title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type IndustryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IndustryQuery = { __typename?: 'Query', industry: { __typename: 'Industry', id: string, title: string, description?: string | null, icon?: string | null, metaTitle?: string | null, metaDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personas?: Array<{ __typename: 'IndustryPersonas', name?: string | null, description?: string | null } | null> | null } };

export type IndustryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IndustryFilter>;
}>;


export type IndustryConnectionQuery = { __typename?: 'Query', industryConnection: { __typename?: 'IndustryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IndustryConnectionEdges', cursor: string, node?: { __typename: 'Industry', id: string, title: string, description?: string | null, icon?: string | null, metaTitle?: string | null, metaDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personas?: Array<{ __typename: 'IndustryPersonas', name?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type NavigationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavigationQuery = { __typename?: 'Query', navigation: { __typename: 'Navigation', id: string, headerCta?: string | null, headerCtaPath?: string | null, hideFromNav?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, desktop?: Array<{ __typename: 'NavigationDesktop', label?: string | null, path?: string | null, submenu?: Array<{ __typename: 'NavigationDesktopSubmenu', label?: string | null, path?: string | null } | null> | null } | null> | null } };

export type NavigationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavigationFilter>;
}>;


export type NavigationConnectionQuery = { __typename?: 'Query', navigationConnection: { __typename?: 'NavigationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavigationConnectionEdges', cursor: string, node?: { __typename: 'Navigation', id: string, headerCta?: string | null, headerCtaPath?: string | null, hideFromNav?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, desktop?: Array<{ __typename: 'NavigationDesktop', label?: string | null, path?: string | null, submenu?: Array<{ __typename: 'NavigationDesktopSubmenu', label?: string | null, path?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type BrandQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BrandQuery = { __typename?: 'Query', brand: { __typename: 'Brand', id: string, company?: string | null, domain?: string | null, tagline?: string | null, subTagline?: string | null, positioning?: string | null, phone?: string | null, email?: string | null, hours?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address?: { __typename: 'BrandAddress', line1?: string | null, line2?: string | null, country?: string | null } | null, social?: { __typename: 'BrandSocial', linkedin?: string | null, instagram?: string | null } | null, founder?: { __typename: 'BrandFounder', name?: string | null, title?: string | null, photo?: string | null, linkedin?: string | null, instagram?: string | null } | null, logo?: { __typename: 'BrandLogo', file?: string | null } | null } };

export type BrandConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BrandFilter>;
}>;


export type BrandConnectionQuery = { __typename?: 'Query', brandConnection: { __typename?: 'BrandConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BrandConnectionEdges', cursor: string, node?: { __typename: 'Brand', id: string, company?: string | null, domain?: string | null, tagline?: string | null, subTagline?: string | null, positioning?: string | null, phone?: string | null, email?: string | null, hours?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address?: { __typename: 'BrandAddress', line1?: string | null, line2?: string | null, country?: string | null } | null, social?: { __typename: 'BrandSocial', linkedin?: string | null, instagram?: string | null } | null, founder?: { __typename: 'BrandFounder', name?: string | null, title?: string | null, photo?: string | null, linkedin?: string | null, instagram?: string | null } | null, logo?: { __typename: 'BrandLogo', file?: string | null } | null } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FooterQuery = { __typename?: 'Query', footer: { __typename: 'Footer', id: string, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, columns?: Array<{ __typename: 'FooterColumns', title?: string | null, type?: string | null, links?: Array<{ __typename: 'FooterColumnsLinks', label?: string | null, path?: string | null, highlight?: boolean | null } | null> | null } | null> | null } };

export type FooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
}>;


export type FooterConnectionQuery = { __typename?: 'Query', footerConnection: { __typename?: 'FooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FooterConnectionEdges', cursor: string, node?: { __typename: 'Footer', id: string, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, columns?: Array<{ __typename: 'FooterColumns', title?: string | null, type?: string | null, links?: Array<{ __typename: 'FooterColumnsLinks', label?: string | null, path?: string | null, highlight?: boolean | null } | null> | null } | null> | null } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'Global', id: string, disclaimer?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, floatingCta?: { __typename: 'GlobalFloatingCta', text?: string | null, buttonLabel?: string | null, buttonPath?: string | null, showAfterScrollPx?: number | null } | null, backToTop?: { __typename: 'GlobalBackToTop', showAfterScrollPx?: number | null } | null, cookieBanner?: { __typename: 'GlobalCookieBanner', text?: string | null, acceptLabel?: string | null, learnMoreLabel?: string | null } | null, scrollAnimation?: { __typename: 'GlobalScrollAnimation', enabled?: boolean | null } | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'Global', id: string, disclaimer?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, floatingCta?: { __typename: 'GlobalFloatingCta', text?: string | null, buttonLabel?: string | null, buttonPath?: string | null, showAfterScrollPx?: number | null } | null, backToTop?: { __typename: 'GlobalBackToTop', showAfterScrollPx?: number | null } | null, cookieBanner?: { __typename: 'GlobalCookieBanner', text?: string | null, acceptLabel?: string | null, learnMoreLabel?: string | null } | null, scrollAnimation?: { __typename: 'GlobalScrollAnimation', enabled?: boolean | null } | null } | null } | null> | null } };

export type ClientLogoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ClientLogoQuery = { __typename?: 'Query', clientLogo: { __typename: 'ClientLogo', id: string, title: string, logo?: string | null, website?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ClientLogoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ClientLogoFilter>;
}>;


export type ClientLogoConnectionQuery = { __typename?: 'Query', clientLogoConnection: { __typename?: 'ClientLogoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ClientLogoConnectionEdges', cursor: string, node?: { __typename: 'ClientLogo', id: string, title: string, logo?: string | null, website?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CountryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CountryQuery = { __typename?: 'Query', country: { __typename: 'Country', id: string, title: string, flagAccent?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personas?: Array<{ __typename: 'CountryPersonas', name?: string | null } | null> | null } };

export type CountryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CountryFilter>;
}>;


export type CountryConnectionQuery = { __typename?: 'Query', countryConnection: { __typename?: 'CountryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CountryConnectionEdges', cursor: string, node?: { __typename: 'Country', id: string, title: string, flagAccent?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personas?: Array<{ __typename: 'CountryPersonas', name?: string | null } | null> | null } | null } | null> | null } };

export type WhyMyelektraQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WhyMyelektraQuery = { __typename?: 'Query', whyMyelektra: { __typename: 'WhyMyelektra', id: string, title: string, description?: string | null, icon?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WhyMyelektraConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WhyMyelektraFilter>;
}>;


export type WhyMyelektraConnectionQuery = { __typename?: 'Query', whyMyelektraConnection: { __typename?: 'WhyMyelektraConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WhyMyelektraConnectionEdges', cursor: string, node?: { __typename: 'WhyMyelektra', id: string, title: string, description?: string | null, icon?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  description
  ogImage
  draft
  heroHeadline
  heroSubtitle
  heroCtaLabel
  heroCtaPath
  storyLabel
  storyHeadline
  storyParagraph1
  storyParagraph2
  missionHeadline
  missionText
  statsHeadline
  includedLabel
  popularBadge
  personasHeadline
  ctaHeadline
  ctaBody
  ctaButtonLabel
  ctaButtonPath
  body
}
    `;
export const SolutionPartsFragmentDoc = gql`
    fragment SolutionParts on Solution {
  __typename
  title
  price
  description
  icon
  isPopular
  bestFor
  cta
  metaTitle
  metaDescription
  steps {
    __typename
    title
    description
  }
  body
}
    `;
export const IndustryPartsFragmentDoc = gql`
    fragment IndustryParts on Industry {
  __typename
  title
  description
  icon
  metaTitle
  metaDescription
  personas {
    __typename
    name
    description
  }
  body
}
    `;
export const NavigationPartsFragmentDoc = gql`
    fragment NavigationParts on Navigation {
  __typename
  desktop {
    __typename
    label
    path
    submenu {
      __typename
      label
      path
    }
  }
  headerCta
  headerCtaPath
  hideFromNav
}
    `;
export const BrandPartsFragmentDoc = gql`
    fragment BrandParts on Brand {
  __typename
  company
  domain
  tagline
  subTagline
  positioning
  phone
  email
  address {
    __typename
    line1
    line2
    country
  }
  hours
  social {
    __typename
    linkedin
    instagram
  }
  founder {
    __typename
    name
    title
    photo
    linkedin
    instagram
  }
  logo {
    __typename
    file
  }
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  columns {
    __typename
    title
    type
    links {
      __typename
      label
      path
      highlight
    }
  }
  copyright
}
    `;
export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  floatingCta {
    __typename
    text
    buttonLabel
    buttonPath
    showAfterScrollPx
  }
  backToTop {
    __typename
    showAfterScrollPx
  }
  cookieBanner {
    __typename
    text
    acceptLabel
    learnMoreLabel
  }
  scrollAnimation {
    __typename
    enabled
  }
  disclaimer
}
    `;
export const ClientLogoPartsFragmentDoc = gql`
    fragment ClientLogoParts on ClientLogo {
  __typename
  title
  logo
  website
  order
}
    `;
export const CountryPartsFragmentDoc = gql`
    fragment CountryParts on Country {
  __typename
  title
  flagAccent
  personas {
    __typename
    name
  }
  order
}
    `;
export const WhyMyelektraPartsFragmentDoc = gql`
    fragment WhyMyelektraParts on WhyMyelektra {
  __typename
  title
  description
  icon
  order
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const SolutionDocument = gql`
    query solution($relativePath: String!) {
  solution(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SolutionParts
  }
}
    ${SolutionPartsFragmentDoc}`;
export const SolutionConnectionDocument = gql`
    query solutionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SolutionFilter) {
  solutionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SolutionParts
      }
    }
  }
}
    ${SolutionPartsFragmentDoc}`;
export const IndustryDocument = gql`
    query industry($relativePath: String!) {
  industry(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IndustryParts
  }
}
    ${IndustryPartsFragmentDoc}`;
export const IndustryConnectionDocument = gql`
    query industryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IndustryFilter) {
  industryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IndustryParts
      }
    }
  }
}
    ${IndustryPartsFragmentDoc}`;
export const NavigationDocument = gql`
    query navigation($relativePath: String!) {
  navigation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavigationParts
  }
}
    ${NavigationPartsFragmentDoc}`;
export const NavigationConnectionDocument = gql`
    query navigationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavigationFilter) {
  navigationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavigationParts
      }
    }
  }
}
    ${NavigationPartsFragmentDoc}`;
export const BrandDocument = gql`
    query brand($relativePath: String!) {
  brand(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BrandParts
  }
}
    ${BrandPartsFragmentDoc}`;
export const BrandConnectionDocument = gql`
    query brandConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BrandFilter) {
  brandConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BrandParts
      }
    }
  }
}
    ${BrandPartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const ClientLogoDocument = gql`
    query clientLogo($relativePath: String!) {
  clientLogo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ClientLogoParts
  }
}
    ${ClientLogoPartsFragmentDoc}`;
export const ClientLogoConnectionDocument = gql`
    query clientLogoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ClientLogoFilter) {
  clientLogoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ClientLogoParts
      }
    }
  }
}
    ${ClientLogoPartsFragmentDoc}`;
export const CountryDocument = gql`
    query country($relativePath: String!) {
  country(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CountryParts
  }
}
    ${CountryPartsFragmentDoc}`;
export const CountryConnectionDocument = gql`
    query countryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CountryFilter) {
  countryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CountryParts
      }
    }
  }
}
    ${CountryPartsFragmentDoc}`;
export const WhyMyelektraDocument = gql`
    query whyMyelektra($relativePath: String!) {
  whyMyelektra(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WhyMyelektraParts
  }
}
    ${WhyMyelektraPartsFragmentDoc}`;
export const WhyMyelektraConnectionDocument = gql`
    query whyMyelektraConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WhyMyelektraFilter) {
  whyMyelektraConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WhyMyelektraParts
      }
    }
  }
}
    ${WhyMyelektraPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    solution(variables: SolutionQueryVariables, options?: C): Promise<{data: SolutionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SolutionQueryVariables, query: string}> {
        return requester<{data: SolutionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SolutionQueryVariables, query: string}, SolutionQueryVariables>(SolutionDocument, variables, options);
      },
    solutionConnection(variables?: SolutionConnectionQueryVariables, options?: C): Promise<{data: SolutionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SolutionConnectionQueryVariables, query: string}> {
        return requester<{data: SolutionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SolutionConnectionQueryVariables, query: string}, SolutionConnectionQueryVariables>(SolutionConnectionDocument, variables, options);
      },
    industry(variables: IndustryQueryVariables, options?: C): Promise<{data: IndustryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IndustryQueryVariables, query: string}> {
        return requester<{data: IndustryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IndustryQueryVariables, query: string}, IndustryQueryVariables>(IndustryDocument, variables, options);
      },
    industryConnection(variables?: IndustryConnectionQueryVariables, options?: C): Promise<{data: IndustryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IndustryConnectionQueryVariables, query: string}> {
        return requester<{data: IndustryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IndustryConnectionQueryVariables, query: string}, IndustryConnectionQueryVariables>(IndustryConnectionDocument, variables, options);
      },
    navigation(variables: NavigationQueryVariables, options?: C): Promise<{data: NavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationQueryVariables, query: string}> {
        return requester<{data: NavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationQueryVariables, query: string}, NavigationQueryVariables>(NavigationDocument, variables, options);
      },
    navigationConnection(variables?: NavigationConnectionQueryVariables, options?: C): Promise<{data: NavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationConnectionQueryVariables, query: string}> {
        return requester<{data: NavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationConnectionQueryVariables, query: string}, NavigationConnectionQueryVariables>(NavigationConnectionDocument, variables, options);
      },
    brand(variables: BrandQueryVariables, options?: C): Promise<{data: BrandQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandQueryVariables, query: string}> {
        return requester<{data: BrandQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandQueryVariables, query: string}, BrandQueryVariables>(BrandDocument, variables, options);
      },
    brandConnection(variables?: BrandConnectionQueryVariables, options?: C): Promise<{data: BrandConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandConnectionQueryVariables, query: string}> {
        return requester<{data: BrandConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandConnectionQueryVariables, query: string}, BrandConnectionQueryVariables>(BrandConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    clientLogo(variables: ClientLogoQueryVariables, options?: C): Promise<{data: ClientLogoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClientLogoQueryVariables, query: string}> {
        return requester<{data: ClientLogoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClientLogoQueryVariables, query: string}, ClientLogoQueryVariables>(ClientLogoDocument, variables, options);
      },
    clientLogoConnection(variables?: ClientLogoConnectionQueryVariables, options?: C): Promise<{data: ClientLogoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClientLogoConnectionQueryVariables, query: string}> {
        return requester<{data: ClientLogoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClientLogoConnectionQueryVariables, query: string}, ClientLogoConnectionQueryVariables>(ClientLogoConnectionDocument, variables, options);
      },
    country(variables: CountryQueryVariables, options?: C): Promise<{data: CountryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CountryQueryVariables, query: string}> {
        return requester<{data: CountryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CountryQueryVariables, query: string}, CountryQueryVariables>(CountryDocument, variables, options);
      },
    countryConnection(variables?: CountryConnectionQueryVariables, options?: C): Promise<{data: CountryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CountryConnectionQueryVariables, query: string}> {
        return requester<{data: CountryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CountryConnectionQueryVariables, query: string}, CountryConnectionQueryVariables>(CountryConnectionDocument, variables, options);
      },
    whyMyelektra(variables: WhyMyelektraQueryVariables, options?: C): Promise<{data: WhyMyelektraQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhyMyelektraQueryVariables, query: string}> {
        return requester<{data: WhyMyelektraQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhyMyelektraQueryVariables, query: string}, WhyMyelektraQueryVariables>(WhyMyelektraDocument, variables, options);
      },
    whyMyelektraConnection(variables?: WhyMyelektraConnectionQueryVariables, options?: C): Promise<{data: WhyMyelektraConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhyMyelektraConnectionQueryVariables, query: string}> {
        return requester<{data: WhyMyelektraConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WhyMyelektraConnectionQueryVariables, query: string}, WhyMyelektraConnectionQueryVariables>(WhyMyelektraConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/e6b15b5f-efe0-4db0-8ec6-531859025cc0/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  